import sys
from collections import defaultdict
import pickle

inp_fp = open(sys.argv[1])
out_fp = open(sys.argv[2], "wb")
job_dict = {} 
job_id = 0 
for line in inp_fp:
    # example line: head -1 ./assign_binding_14a_open.sh
    # python scripts/assign_binding_for_each_read_multiple_conditions.py peak_per_orange_vs_footprint_length/suppressed_merged_S2_to_all_open_and_closed_mnase_peaks_cluster_199_lf_15_rf_15_po_vs_footplen_for_site_peak_1291_1_sam_flag_99~147.tsv peak_footprints/suppressed_merged_S2_to_all_open_and_closed_mnase_peaks_cluster_199_lf_15_rf_15_methylation_matrix_for_site_peak_1291_1_sam_flag_99~147.tsv binding_labeled_reads_for_peak/suppressed_merged_S2_to_all_open_and_closed_mnase_peaks_cluster_199_lf_15_rf_15_site_peak_1291_1_sam_flag_99~147_binding_label.cond1.tsv binding_labeled_reads_for_peak/suppressed_merged_S2_to_all_open_and_closed_mnase_peaks_cluster_199_lf_15_rf_15_site_peak_1291_1_sam_flag_99~147_binding_label.cond2.tsv binding_labeled_reads_for_peak/suppressed_merged_S2_to_all_open_and_closed_mnase_peaks_cluster_199_lf_15_rf_15_site_peak_1291_1_sam_flag_99~147_binding_label.cond3.tsv binding_labeled_reads_for_peak/suppressed_merged_S2_to_all_open_and_closed_mnase_peaks_cluster_199_lf_15_rf_15_site_peak_1291_1_sam_flag_99~147_binding_label.cond4.tsv binding_labeled_reads_for_peak/suppressed_merged_S2_to_all_open_and_closed_mnase_peaks_cluster_199_lf_15_rf_15_site_peak_1291_1_sam_flag_99~147_binding_label.cond5.tsv binding_labeled_reads_for_peak/suppressed_merged_S2_to_all_open_and_closed_mnase_peaks_cluster_199_lf_15_rf_15_site_peak_1291_1_sam_flag_99~147_binding_label.cond6.tsv peak_per_orange_vs_footprint_length/suppressed_merged_S2_to_all_open_and_closed_mnase_peaks_cluster_199_lf_15_rf_15_per_methylation_for_site_peak_1291_1_sam_flag_99~147.pkl binding_labeled_reads_for_peak/suppressed_merged_S2_to_all_open_and_closed_mnase_peaks_cluster_199_lf_15_rf_15_site_peak_1291_1_sam_flag_99~147_binding_label.cond7.tsv binding_labeled_reads_for_peak/suppressed_merged_S2_to_all_open_and_closed_mnase_peaks_cluster_199_lf_15_rf_15_site_peak_1291_1_sam_flag_99~147_binding_label.cond8.tsv occluded_edges_on_methylation_vec/suppressed_merged_S2_to_all_open_and_closed_mnase_peaks_lf_15_rf_15_min_flen_10_wobble_gap_1_occluded.pkl footprint_min_size_selection/suppressed_merged_S2_to_all_open_and_closed_mnase_peaks_lf_15_rf_15_tf_footprint_min_length_10_wobble_gap_1.pkl
    l_items = line.strip().split(" ")
    job_dict[job_id]  = l_items[2: ]
     
    job_id +=1 

pickle.dump(job_dict, out_fp)
out_fp.close()
inp_fp.close() 

